### ISSUE TITLE
Unnecessary warning for tibble formatted data objects?

### ISSUE THREAD

**Issue by SchmidtPaul** [kwstat/desplot#4]
Hi,
I have recently been getting this warning whenever I supply a `tibble` to the `data =` argument. 
```
## Warning in if (class(data) == "formula") {: the condition has length > 1 and only
## the first element will be used
```
Notice that this warning disappears if I write `data = as.data.frame(tibble)`.

**Comment by kwstat** [comment]
Thanks. Fixed. Update now on CRAN.
