### ISSUE TITLE
Enforce `nrow = 1` with `|location`?

### ISSUE THREAD

**Issue by SchmidtPaul** [kwstat/desplot#7]
With my current desplots, the visual information gain when including `|block` for blocks within a single trial is great. However, when it comes to exporting the graph I usually run into the blocks being shown in multiple rows of the plot. Is there a hack to force them to all be on the same row?

``` r
library(tidyverse)
library(desplot)

dat <- tibble::tribble(
  ~row, ~col, ~rep, ~id,
  1L,   1L,   1L, "A",
  2L,   1L,   1L, "B",
  1L,   2L,   2L, "B",
  2L,   2L,   2L, "A",
  1L,   3L,   3L, "B",
  2L,   3L,   3L, "A",
  1L,   4L,   4L, "B",
  2L,   4L,   4L, "A",
)

desplot(dat, 
        id ~ col + row,
        text = id, cex = 1)
```

![](https://i.imgur.com/G2OkRTV.png)

``` r
desplot(dat, 
        id ~ col + row | rep,
        text = id, cex = 1)
```

![](https://i.imgur.com/iK6XYef.png)

<sup>Created on 2022-02-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kwstat** [comment]
If I understand correctly, I think you want the `layout` argument of lattice:
```
desplot(dat, 
        id ~ col + row | rep,
        text = id, cex = 1,
        layout=c(4,1))
```
![desplot](https://user-images.githubusercontent.com/484260/153621587-f2225dc9-4d4a-430b-a9c2-78010e583044.png)
