### ISSUE TITLE
position of first plot

### ISSUE THREAD

**Issue by webbchen** [kwstat/desplot#8]
Dear developers

How can I get the first plot to be shown in the left upper corner?
As input I've got rows (r). columns (c) and for the text the plot numbers (plot) and the colours representing the residuals (res) of a disease score.
```
desplot(experiment1, res ~ c + r, text = plot, cex = 0.5, gg = T, col.regions = c("maroon", "gray97","slateblue"), 
main = "some title text")
```
At the moment the graph is upside down with plot 1 in the left lower corner. (Title edited out.)
![testgraph](https://user-images.githubusercontent.com/12898402/191308107-a5c8921a-6d69-4474-8ef0-0f319f7af426.png)

Many thanks,

A Webb

**Comment by kwstat** [comment]
Please try to provide reproducible examples when you can.
If I understand correctly, I think you want to add `flip=TRUE`:
```
require(agridat)
require(desplot)
desplot(yates.oats, block ~ col+row,
        col=nitro, text=gen, cex=1, aspect=511/176,
        out1=block, out2=gen, 
        gg=TRUE, flip=TRUE,
        out2.gpar=list(col = "gray50", lwd = 1, lty = 1))
```

**Comment by webbchen** [comment]
Thank you, ```flip=T``` did it.
