### ISSUE TITLE
Removing White Space

### ISSUE THREAD

**Issue by SchmidtPaul** [kwstat/desplot#9]
Hi, in the reprex below I show how I usually get rid of white space / empty areas in certain desplots. I simply want to ask: Is this optimal or would you recommend a different approach? Especially the `c(0.6, 1.4)` seems arbitrary to me.

``` r
library(desplot)
library(tidyverse)

dat <- tibble(
  var = letters[1:6],
  block = as.factor(c(1, 1, 1, 2, 2, 2)),
  row = 1L,
  col = 1:6
)

d <- desplot(data = dat,
             form = var ~ col + row | block)

d
```

![](https://i.imgur.com/HT8sMrc.png)

``` r

update(d, ylim = c(0.6, 1.4))
```

![](https://i.imgur.com/3dxuQIO.png)

<sup>Created on 2022-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kwstat** [comment]
Fix via https://github.com/kwstat/desplot/commit/1e70933e2a8b800b51029101e6390b82e946e813
Please test.
![desplot_1row](https://user-images.githubusercontent.com/484260/209259270-052ff860-6472-46e3-a5c6-2fa8f06d9df0.png)

**Comment by SchmidtPaul** [comment]
Works for me!
